package testapp;


/**
* testapp/data.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test1.idl
* Sunday, October 6, 2024 6:46:25 PM CEST
*/

public final class data implements org.omg.CORBA.portable.IDLEntity
{
  public int p = (int)0;
  public int m = (int)0;
  public int id= (int)0;
  public data ()
  {
  } // ctor

  public data (int _p, int _m,int _id)
  {
    id= _id;
    p = _p;
    m = _m;
  } // ctor

} // class data
