package testapp;


/**
* testapp/matchData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Wednesday, October 9, 2024 6:14:12 PM CEST
*/

public final class matchData implements org.omg.CORBA.portable.IDLEntity
{
  public int k = (int)0;
  public int id = (int)0;

  public matchData ()
  {
  } // ctor

  public matchData (int _k, int _id)
  {
    k = _k;
    id = _id;
  } // ctor

} // class matchData
