package testapp;


/**
* testapp/Test1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Wednesday, October 9, 2024 6:14:12 PM CEST
*/

public interface Test1 extends Test1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Test1
