package testapp;

/**
* testapp/Test1Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Tuesday, October 8, 2024 5:21:08 PM CEST
*/

public final class Test1Holder implements org.omg.CORBA.portable.Streamable
{
  public testapp.Test1 value = null;

  public Test1Holder ()
  {
  }

  public Test1Holder (testapp.Test1 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = testapp.Test1Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    testapp.Test1Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return testapp.Test1Helper.type ();
  }

}
