package testapp;


/**
* testapp/Test1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Tuesday, October 8, 2024 5:21:08 PM CEST
*/

public interface Test1 extends Test1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Test1
