package testapp;


/**
* testapp/Test1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Tuesday, October 8, 2024 5:21:08 PM CEST
*/

public interface Test1Operations 
{
  testapp.data matchMe ();
  testapp.data movePeice (testapp.data d);
  void shutdown ();
} // interface Test1Operations
