package testapp;


/**
* testapp/Test1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test1.idl
* Wednesday, October 9, 2024 6:14:12 PM CEST
*/

public interface Test1Operations 
{
  testapp.matchData matchMe ();
  testapp.data movePeice (testapp.data d);
  void shutdown ();
} // interface Test1Operations
