package testapp;


/**
* testapp/Test1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test1.idl
* Friday, October 11, 2024 5:08:09 PM CEST
*/

public interface Test1Operations 
{
  testapp.matchData matchMe ();
  testapp.data movePeice (testapp.data d);
  void update (int id);
  void shutdown ();
} // interface Test1Operations
