package testapp;


/**
* testapp/Test1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test1.idl
* Sunday, October 6, 2024 6:46:25 PM CEST
*/

public interface Test1Operations 
{
  testapp.data matchMe ();
  testapp.data movePeice (testapp.data d);
  void shutdown ();
} // interface Test1Operations
