package testapp;


/**
* testapp/Test1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test1.idl
* Sunday, October 6, 2024 6:46:25 PM CEST
*/

public interface Test1 extends Test1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Test1
